# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Runna' do
  config = use_native_modules!

  # React Native Maps dependency
  pod 'react-native-maps', path: '../node_modules/react-native-maps'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # Uncomment the following lines if you need Google Maps support on iOS
  # pod 'react-native-google-maps', path: '../node_modules/react-native-maps'
  # pod 'GoogleMaps'
  # pod 'Google-Maps-iOS-Utils'

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'RunnaTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-permissions'
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
            '$(inherited)',
  
            ## Add this line for each permission you want to use in your project
            ## You can find all available permissions in the `app.json` of the example app
            ## https://github.com/zoontek/react-native-permissions/blob/master/example/ios/Uber/app.json
  
            'PERMISSIONS=1',
            'PERMISSIONS_LOCATION_WHEN_IN_USE=1',
            'PERMISSIONS_LOCATION_ALWAYS=1'
          ]
        end
      end
    end
  end
end